### ISSUE TITLE
Erreur lors de l'accès à la page du plugin (après installation)

### ISSUE THREAD

**Issue by DerMouse** [franck-paul/piwik#3]
L'installation s'est bien faite (Dotclear 2.31.1).

Quand j'essaye d'accéder à la page de configuration du plugin, j'ai une erreur :

 Dotclear\Plugin\piwik\Piwik::parseServiceURI(): Argument #2 ($base) must be of type string, null given, called in /XXX/plugins/piwik/src/Piwik.php on line 36

![Shutter-569](https://github.com/user-attachments/assets/0c001baa-d54b-490e-ba6b-eb5e3ad3bb87)

**Comment by franck-paul** [comment]
Effectivement, je corrige et je publie une nouvelle version

**Comment by franck-paul** [comment]
La release 1.1 devrait corriger ça.
