### ISSUE TITLE
Problème configuration greffon

### ISSUE THREAD

**Issue by DerMouse** [franck-paul/piwik#4]
La config du plugin demande deux informations : l'URL de Matomo, et un token.
![Shutter-579](https://github.com/user-attachments/assets/b9b70e99-43a9-46d0-82d1-6e7bfaaf57c4)

 Il *semble* que les tokens utilisés par matomo soient maintenant de simples entiers (indice du site suivi par cette instance Mtm -- je concède que cela me paraît bizarre). Voilà le JS que Matomo suggère d'insérer dans les bas de pages : 

![Shutter-582](https://github.com/user-attachments/assets/b3465568-6c73-448b-a332-76fb56974623)

Si l'on fait ce qui semble logique (URL / indice numérique), le plugin n'aime pas : 

![Shutter-580](https://github.com/user-attachments/assets/32bbabe1-859f-4352-9b21-a11f6c84d7b3)

**Comment by franck-paul** [comment]
Le token n'est pas l'ID du site suivi, c'est un token d'API.

À créer dans les settings de Matomo : Personnel > Sécurité > Jetons d'authentification

**Comment by DerMouse** [comment]
J'ai regardé ça, et... il y a qq chose qui me gêne (mais qui peut venir de mon manque de compréhension de « comment ça marche ». Sur Matomo, lors de la création d'un jeton, il est bien indiqué que « secret, ne partager avec personne, équivalent à votre compte/mot de passe » : 

![Shutter-583](https://github.com/user-attachments/assets/d377c03b-7b44-43ec-9745-3ec8ffaf1348)

Si ça reste purement interne à DC qui s'en sert pour..., pas de difficulté, mais si c'est envoyé avec du JS vers les navigateurs des internautes, ça me paraît plus délicat.

En supposant que ce jeton reste local à DC, quand je l'utilise dans la config du plugin, soit l'URL n'est pas acceptée (si je mets juste le nom, toto.mon.domaine) 

![Shutter-584](https://github.com/user-attachments/assets/9d32d78e-cd61-426f-999b-e01c41b52d78)

soit, si je préfixe par https, ça se passe moyennement bien : 

![Shutter-585](https://github.com/user-attachments/assets/f8c231eb-74be-4570-938b-587c65cf3027)

**Comment by franck-paul** [comment]
Ma config qui fonctionne avec une installation concurrente sur mon Mac :

URL Piwik : http://localhost.local/matomo/index.php
Token Piwik : d3e2c51246de6e5f6c4b1a49c33514d8 (exemple)

Et je viens juste de constater que je ne suis pas en HTTPS.

Va falloir que je fouille un peu…

**Comment by franck-paul** [comment]
Tu as quelle version de Matomo ?

**Comment by DerMouse** [comment]
> Tu as quelle version de Matomo ?

La 5.1.1 (avant-dernière, la 5.1.2 semble sortie il y a peu de temps).

**Comment by DerMouse** [comment]
> Et je viens juste de constater que je ne suis pas en HTTPS.

Je vais faire le test en HTTP, pour voir.

**Comment by DerMouse** [comment]
En http (URL indiquée http://localhost), la page de config du plugin ne m'insulte plus mais dit juste « aucun site piwik configuré ».

![Shutter-586](https://github.com/user-attachments/assets/12425ee3-6b1f-42b9-aaa5-3999f9df28ab)

Le contenu de la base (partiel) : 

select * from dc_setting where setting_id like '%piwi%';
+-------------------+---------+------------+------------------------------------------------------------------------+--------------+---------------+
| setting_id        | blog_id | setting_ns | setting_value                                                          | setting_type | setting_label |
+-------------------+---------+------------+------------------------------------------------------------------------+--------------+---------------+
| piwik_service_uri | default | piwik      | http://localhost/index.php?token_auth=abcdefabcdef | string       |               |
| piwik_site        | default | piwik      |                                                                        | string       |               |
| piwik_ips         | default | piwik      |                                                                        | string       |               |
| piwik_fancy       | default | piwik      | 0                                                                      | boolean      |               |
+-------------------+---------+------------+------------------------------------------------------------------------+--------------+---------------+

**Comment by franck-paul** [comment]
Au début c'est normal, il faut créer le site Piwik en bas (ça utilise l'API) ou le faire côté Matomo. Une fois effectué un refresh permet de sélectionner le blog à suivre dans la liste déroulante.

**Comment by franck-paul** [comment]
Quoi qu'il en soit, l'utilisation de Matomo en local ne fonctionne franchement pas bien (pb de certif et de support du schéma ssl qui peut poser problème sans compter les résolutions DNS).

Je pense qu'il faudrait revoir tout ça en profondeur mais là tout de suite j'ai un peu la flemme (je sors d'une semaine de staff Paris Web et c'est fatigant).

**Comment by franck-paul** [comment]
Je suis en train de revoir le code et il restera le problème local de la chaîne de signature du certificat (dans ce cas là il faudra passer en mode DEV+DEBUG pour bypasser le contrôle — à ne faire qu'en local donc, c'est risky).

Une nouvelle version à venir…
