### ISSUE TITLE
The type attribute is unnecessary for JavaScript resources.

### ISSUE THREAD

**Issue by Philippe-dev** [franck-paul/piwik#7]
Dans src/piwik.php peut-on enlever cet attribut dans les balises <script> ?
(et aussi peut-être le slash fermant la balise img ?)

**Comment by franck-paul** [comment]
Je regarde dès que j'ai un moment (demain je pense)

**Comment by franck-paul** [comment]
Ah oui, c'est du vieux code (et ça rejoint le #5)
